<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>RevitUsdExportSDK2026</AssemblyName>
    <RootNamespace>RevitUsdExportSDK</RootNamespace>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <Deterministic>false</Deterministic>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <DefineConstants>TRACE;DEBUG;REV2026</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DefineConstants>TRACE;REV2026</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\bindings\**\*.cs" Link="bindings\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="revit_all_main_versions_api_x64" Version="2025.0.0" PrivateAssets="all" />
    <PackageReference Include="newtonsoft.json" Version="13.0.1" PrivateAssets="all" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.3" PrivateAssets="all" />
    <PackageReference Include="system.windows.extensions" Version="8.0.0" PrivateAssets="all" />
  </ItemGroup>
</Project>
